# Database vars
dmapi_galera_address: "{{ galera_address | default('127.0.0.1') }}"
dmapi_galera_database: dmapi
dmapi_galera_user: dmapi
dmapi_galera_use_ssl: "{{ galera_use_ssl | default(False) }}"
dmapi_galera_ssl_ca_cert: "{{ galera_ssl_ca_cert | default('/etc/ssl/certs/galera-ca.pem') }}"
dmapi_galera_password: "{{DMAPI_MYSQL_PASSWORD}}"
dmapi_galera_port: 3306

# RPC
dmapi_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group | default('rabbitmq_all') }}"
dmapi_oslomsg_rpc_setup_host: "{{ (dmapi_oslomsg_rpc_host_group in groups) | ternary(groups[dmapi_oslomsg_rpc_host_group][0], 'localhost') }}"
dmapi_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport | default('rabbit') }}"
dmapi_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers | default('127.0.0.1') }}"
dmapi_oslomsg_rpc_port: "{{ oslomsg_rpc_port | default('5672') }}"
dmapi_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl | default(False) }}"
dmapi_oslomsg_rpc_userid: dmapi
dmapi_oslomsg_rpc_vhost: /dmapi
dmapi_oslomsg_rpc_ssl_version: "{{ oslomsg_rpc_ssl_version | default('TLSv1_2') }}"
dmapi_oslomsg_rpc_ssl_ca_file: "{{ oslomsg_rpc_ssl_ca_file | default('') }}"
dmapi_oslomsg_rpc_password: "{{RABBITMQ_PASSWORD}}"

# Notify
dmapi_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group | default('rabbitmq_all') }}"
dmapi_oslomsg_notify_setup_host: "{{ (dmapi_oslomsg_notify_host_group in groups) | ternary(groups[dmapi_oslomsg_notify_host_group][0], 'localhost') }}"
dmapi_oslomsg_notify_transport: "{{ oslomsg_notify_transport | default('rabbit') }}"
dmapi_oslomsg_notify_servers: "{{ oslomsg_notify_servers | default('127.0.0.1') }}"
dmapi_oslomsg_notify_port: "{{ oslomsg_notify_port | default('5672') }}"
dmapi_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl | default(False) }}"
dmapi_oslomsg_notify_userid: "{{ dmapi_oslomsg_rpc_userid }}"
dmapi_oslomsg_notify_password: "{{ dmapi_oslomsg_rpc_password }}"
dmapi_oslomsg_notify_vhost: "{{ dmapi_oslomsg_rpc_vhost }}"

# Set the host which will execute the shade modules
# for the service setup. The host must already have
# clouds.yaml properly configured.

dmapi_service_setup_host: "{{ openstack_service_setup_host | default('localhost') }}"
dmapi_service_setup_host_python_interpreter: "{{ openstack_service_setup_host_python_interpreter | default((dmapi_service_setup_host == 'localhost') | ternary(ansible_playbook_python, ansible_python['executable'])) }}"

# Keystone AuthToken/Middleware
dmapi_keystone_auth_plugin: password
dmapi_service_project_domain_id: default
dmapi_service_user_domain_id: default
dmapi_service_project_name: "service"


## Service Type and Data
dmapi_service_name: "dmapi"
dmapi_service_user_name: "dmapi"
dmapi_service_type: datamover
dmapi_service_description: "Trilio Datamover"
dmapi_service_role_name: "admin"
dmapi_service_password: "{{DMAPI_SERVICE_PASSWORD}}"
dmapi_service_region: "{{nova_service_region}}"
dmapi_service_host: "{{ openstack_service_bind_address | default('0.0.0.0') }}"
dmapi_service_port: 8784
dmapi_service_proto: http
dmapi_service_publicuri_proto: "{{ openstack_service_publicuri_proto | default(dmapi_service_proto) }}"
dmapi_service_adminuri_proto: "{{ openstack_service_adminuri_proto | default(dmapi_service_proto) }}"
dmapi_service_internaluri_proto: "{{ openstack_service_internaluri_proto | default(dmapi_service_proto) }}"
dmapi_service_publicurl: "{{ dmapi_service_publicuri_proto }}://{{ external_lb_vip_address }}:{{ dmapi_service_port }}"
dmapi_service_internalurl: "{{ dmapi_service_internaluri_proto }}://{{ internal_lb_vip_address }}:{{ dmapi_service_port }}"
dmapi_service_adminurl: "{{ dmapi_service_adminuri_proto }}://{{ internal_lb_vip_address }}:{{ dmapi_service_port }}"

## New Vars
trilio_apt_repo_file_path: /etc/apt/sources.list.d/triliovault.list
trilio_yum_repo_file_path: /etc/yum.repos.d/triliovault.repo

DMAPI_LOG_DIR: "/var/log/triliovault"
DMAPI_LOG_FILE: "{{ DMAPI_LOG_DIR }}/dmapi.log"
DMAPI_LOG_CONF: "/etc/triliovault-datamover/datamover_api_logging.conf"


dmapi_cfg_dir: "/etc/triliovault-datamover"
dmapi_cfg_file: "{{ dmapi_cfg_dir }}/triliovault-datamover-api.conf"
