---
- name: Install packages on datamover api container | centos-release-openstack-{{OPENSTACK_DIST}}
  yum:
    update_cache: yes
    name:
      - "centos-release-openstack-{{OPENSTACK_DIST | lower}}"
    state: latest

- name: install packages on datamover api container | {{ PYTHON_VERSION }} devel and nova packages
  yum:
    update_cache: yes
    name:
      - "{{ PYTHON_VERSION }}-devel"
      - "{{ PYTHON_VERSION }}-nova"
    state: latest

- name: create /tmp/datamover_url
  template:
     src: datamover_url
     dest: /tmp/datamover_url
   
- name: create yum repo file in if  ansible_distribution is Centos/RHEL
  template:
     src: trilio.repo
     dest: "{{trilio_yum_repo_file_path}}"

- name: install tvault-datamover-api rpm package when using python2
  yum:
    update_cache: yes
    name: dmapi
    state: latest
  notify:
      - restart tvault-datamover-api
  when: PYTHON_VERSION=="python2"
      
- name: install tvault-datamover-api rpm package when using python3
  yum:
    update_cache: yes
    name: python3-dmapi
    state: latest
  notify:
      - restart tvault-datamover-api
  when: PYTHON_VERSION=="python3"

- name: Create dmapi group
  group:
    name: "{{DMAPI_GRP}}"
    state: present
    system: yes

- name: Create dmapi User
  user:
    name: "{{DMAPI_USR}}"
    groups: "{{DMAPI_GRP}}"
    shell: "/bin/false"
    home: "/var/lib/{{DMAPI_USR}}"
    create_home: no
    system: yes

- name: change permission of datamover log file 
  file: path={{datamover_log_dir}} owner={{DMAPI_USR}} group={{DMAPI_GRP}} state=directory recurse=yes
  notify:
      - restart tvault-datamover-api

- name: find out path of dmapi bianry 
  shell: which dmapi-api
  register: dmapi_bin

- name: execute populate-conf binary
  shell: populate-conf
  register: populate_conf
  notify:
      - restart tvault-datamover-api

- name: create tvault-datamover-api service in systemd if ansible_distribution is Centos/RHEL
  template:
     src: tvault_datamover_service.j2
     dest: "{{datamover_service_file_path}}"
  register: create_systemd
  notify:
      - restart tvault-datamover-api

- name: enable and daemon reload tvault-datamover-api service
  shell: systemctl daemon-reload && systemctl enable tvault-datamover-api.service
  when: populate_conf.changed or create_systemd.changed
  notify:
      - restart tvault-datamover-api

- name: ensure /tmp/datamover_url file is deleted
  file: path="/tmp/datamover_url" state=absent