---

- name: get python details
  import_tasks: get_python.yml
  tags:
    - tvault-datamover-api
    - tvault-all-install
    - tvault-datamover-api-uninstall
    - tvault-all-uninstall

- name: generate password
  import_tasks: generate_password.yml
  tags:
      - tvault-datamover-api
      - tvault-all-install

- name: uninstall tvault_datamover_api
  import_tasks: uninstall.yml
  tags:
   - tvault-datamover-api-uninstall
   - tvault-all-uninstall

- name: Database and RabbitMQ
  import_tasks: create_dmapi_db.yml
  tags:
    - tvault-datamover-api
    - tvault-all-install

- name: Create Opensatck Endpoints
  import_tasks: create_endpoint.yml
  tags:
    - tvault-datamover-api
    - tvault-all-install

- name:  install tvault_datamover_api on rhel/centos
  import_tasks: install_rhel.yml
  tags:
       - tvault-datamover-api
       - tvault-all-install
  when: >
       (ansible_distribution_major_version=="7" and ansible_distribution=="CentOS") or
       (ansible_distribution_major_version=="7" and ansible_distribution=="RedHat") or
       (ansible_distribution_major_version=="8" and ansible_distribution=="CentOS") or
       (ansible_distribution_major_version=="8" and ansible_distribution=="RedHat")

- name:  install tvault_datamover_api on ubuntu
  import_tasks: install_ubuntu.yml
  tags:
       - tvault-datamover-api
       - tvault-all-install
  when: ansible_distribution=="Ubuntu"

- name: Synchronize the Dmapi schema and generate connection string
  import_tasks: synchronize_dmapi_db.yml



