apiVersion: v1
description: OpenStack-Helm Helm-Toolkit
home: https://docs.openstack.org/openstack-helm
icon: https://www.openstack.org/themes/openstack/images/project-mascots/OpenStack-Helm/OpenStack_Project_OpenStackHelm_vertical.png
maintainers:
- name: OpenStack-Helm Authors
name: helm-toolkit
sources:
- https://opendev.org/openstack/openstack-helm-infra
- https://opendev.org/openstack/openstack-helm
version: 0.1.0-mcp-2792
