---

- name: Setup trilio yum repo for queens
  template:
     src: trilio.repo
     dest: "{{trilio_yum_repo_file_path}}"

- name: install tvault horizon plugin packages when using python2
  yum:
     update_cache: yes
     name:
        - workloadmgrclient
        - tvault-horizon-plugin
     state: latest
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python2"

- name: install tvault horizon plugin packages when using python3 ansible_distribution_major_version=="7"
  yum:
     update_cache: yes
     name:
        - python3-workloadmgrclient-el7
        - python3-tvault-horizon-plugin
     state: latest
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python3" and ansible_distribution_major_version=="7"

- name: install tvault horizon plugin packages when using python3 ansible_distribution_major_version=="8"
  yum:
     update_cache: yes
     name:
        - python3-workloadmgrclient-el8
        - python3-tvault-horizon-plugin
     state: latest
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python3" and ansible_distribution_major_version=="8"
