---
- name: remove all python files from openstack_dashboard directory
  file: path="{{HORIZON_PATH}}/openstack_dashboard/local/enabled/{{item}}" state=absent
  with_items:
    - tvault_panel_group.py
    - tvault_admin_panel_group.py
    - tvault_panel.py
    - tvault_admin_panel.py
    - tvault_settings_panel.py
  notify:
     - restart webserver

- name: remove tvault_filter.py file from openstack_dashboard diretory
  file: path="{{HORIZON_PATH}}/openstack_dashboard/templatetags/tvault_filter.py" state=absent
  notify:
     - restart webserver

- block:
    - copy: src="{{automation_home}}/files/sync_static1.py" dest="/tmp/sync_static1.py" 
    - shell: "{{virtual_env}} && {{PYTHON_VERSION}} {{ MANAGE_FILE }} shell < /tmp/sync_static1.py &> /dev/null"
      args:
         chdir: "{{HORIZON_PATH}}"
    - file: path=/tmp/sync_static1.py state=absent
