---
- name: remove all python files from openstack_dashboard directory
  file: path="{{HORIZON_PATH}}/openstack_dashboard/local/enabled/{{item}}" state=absent
  with_items:
    - tvault_panel_group.py
    - tvault_admin_panel_group.py
    - tvault_panel.py
    - tvault_admin_panel.py
    - tvault_settings_panel.py

- name: remove tvault_filter.py file from openstack_dashboard diretory
  file: path="{{HORIZON_PATH}}/openstack_dashboard/templatetags/tvault_filter.py" state=absent

- block:
    - copy: src="{{automation_home}}/files/sync_static1.py" dest="/tmp/sync_static1.py" 
    - shell: ./manage.py shell < /tmp/sync_static1.py &> /dev/null 
      args:
         chdir: "{{HORIZON_PATH}}"
    - file: path=/tmp/sync_static1.py state=absent

- name: uninstall tvault horizon plugin packages
  yum:
     update_cache: yes
     name:
        - tvault-horizon-plugin
        - python-workloadmgrclient
     state: absent

- name: restart webserver service
  service: name={{WebServer}} state=restarted
