---
- name: uninstall tvault horizon plugin packages when using python2
  yum:
     update_cache: yes
     name:
        - tvault-horizon-plugin
     state: absent
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python2"
  
- name: uninstall tvault horizon plugin packages when using python3 and ansible_distribution_major_version=="7"
  yum:
     update_cache: yes
     name:
        - python3-tvault-horizon-plugin
        - python3-workloadmgrclient-el7
     state: absent
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python3" and ansible_distribution_major_version=="7"

- name: uninstall tvault horizon plugin packages when using python3 and ansible_distribution_major_version=="8"
  yum:
     update_cache: yes
     name:
        - python3-tvault-horizon-plugin-el8
     state: absent
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python3" and ansible_distribution_major_version=="8"
