---
- name: Stop tvault-objetc-store service if running
  service: name=tvault-object-store state=stopped
  ignore_errors: yes

- name: Stop tvault-contego service if running
  service: name=tvault-contego state=stopped
  ignore_errors: yes

- name: Reload Daemon
  shell: systemctl daemon-reload

- name: Load nbd and create 128 devices
  lineinfile:
    path: /etc/rc.modules
    line: 'depmod -a && sudo modprobe nbd nbds_max=128'
    create: yes
  register: chk_nbd

- debug:
    msg: "{{ chk_nbd }}"

- name: Download contego virtenv deb package
  shell: |
          curl -Og6 http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/tvault-contego-extension_{{ TVAULT_PACKAGE_VERSION }}_all.deb
          dpkg --configure -a && apt-get -o Dpkg::Options::="--force-confold" install ./tvault-contego-extension_{{TVAULT_PACKAGE_VERSION}}_all.deb -y
          rm -rf ./tvault-contego-extension_{{ TVAULT_PACKAGE_VERSION }}_all.deb

- debug : msg="curl -Og6 http://{{IP_ADDRESS}}:{{ PORT_NO }}/deb-repo/deb-repo/tvault-contego-extension_{{TVAULT_PACKAGE_VERSION}}_all.deb" verbosity={{ verbosity_level }}

- name: install tvault-contego deb package when using python2
  shell: |
          curl -Og6 http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/tvault-contego_{{ TVAULT_PACKAGE_VERSION  }}_all.deb
          dpkg --configure -a && apt-get -o Dpkg::Options::="--force-confold" install ./tvault-contego_{{ TVAULT_PACKAGE_VERSION }}_all.deb -y
          rm -rf tvault-contego_{{ TVAULT_PACKAGE_VERSION }}_all.deb
  when: PYTHON_VERSION=="python2"

- name: install python3-tvault-contego deb package when using python3
  shell: |
          curl -Og6 http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/python3-tvault-contego_{{ TVAULT_PACKAGE_VERSION }}_all.deb
          dpkg --configure -a && apt-get -o Dpkg::Options::="--force-confold" install ./python3-tvault-contego_{{ TVAULT_PACKAGE_VERSION }}_all.deb -y
          rm -rf python3-tvault-contego_{{ TVAULT_PACKAGE_VERSION }}_all.deb
  when: PYTHON_VERSION=="python3"


