---

- hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install lxc packages
      package:
        update_cache: yes
        name:
          - "lxc"
          - "python3-lxc"
          - "lxc-templates"
        state: present
      tags: [ 'never', 'tvault_pre_install']

- name: Installation and setup of dmapi conatiner
  hosts: dmapi_all 
  gather_facts: "{{ osa_gather_facts | default(True) }}"
  user: root
  environment: "{{ deployment_environment_variables | default({}) }}"
  vars_files:
    - "defaults/repo_packages/openstack_services.yml"
    - "defaults/{{ install_method }}_install.yml"
  pre_tasks:
    - include_tasks: "common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
      when: not is_metal

    - include_tasks: common-tasks/unbound-clients.yml
      when:
        - hostvars['localhost']['resolvconf_enabled'] | bool
  roles:
    - role: ansible-datamover-api

- hosts: tvault_compute_hosts
  roles:
    - role: ansible-tvault-contego-extension

- hosts: horizon_all
  roles:
    - role: ansible-horizon-plugin
